services:
  db:
    image: postgres:16-alpine
    container_name: runshare-db
    restart: always
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: pass_postgres
      POSTGRES_DB: runshare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
